name: dart_application_saveload_manager_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  archive: ^4.0.7
  http_parser: ^4.1.2
  ini: ^2.1.0
  intl: ^0.20.2
  mime: ^2.0.0
  path: ^1.9.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
